auth_sys/urls.py
from django.conf.urls import url

from .views import ApplicationRegistrationView, ApplicationUpdateView, CustomAuthorizationView
from auth_sys.views.oauth_token_redirect import oauth_token_redirect

urlpatterns = [
    url(r'^oauth_redirect/$', oauth_token_redirect),
    url(r'^authorize/$', CustomAuthorizationView.as_view(), name='authorize'),
    url(r'^applications/register/$', ApplicationRegistrationView.as_view(), name='register'),
    url(r'^applications/(?P<pk>[\w-]+)/update/$', ApplicationUpdateView.as_view(), name='update'),
]

app_name = "auth_sys"

my_to_do/urls.py
import os

from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from my_to_do.views import home, mytodo_login, login_view, mytodo_logout,\
    mytodo_whoami
# from django.urls.conf import path

settings_module = os.getenv('DJANGO_SETTINGS_MODULE', 'my_to_do.settings_dev')

if settings_module == 'my_to_do.settings_dev':
    from my_to_do.settings_dev import DEBUG
    from my_to_do import settings_dev as settings
else:
    from my_to_do.settings_prod import DEBUG
    from my_to_do import settings_prod as settings

urlpatterns = [
    url(r'^$', home),
    url(r'^login/$', mytodo_login),
    url(r'^logout/$', mytodo_logout),
    url(r'^accounts/login/$', login_view),
    url(r'^me/$', mytodo_whoami),
    url(r'^cr_review/', include("cr_review_sys.url")),
    url(r'^md_analysis/', include("md_analysis.url")),
    url(r'^o/', include("auth_sys.urls", namespace='oauth')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
#     path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if DEBUG:
    urlpatterns += [
        url(r'^admin/', admin.site.urls),
    ]

auth_sys/models.py
import os
from uuid import uuid4

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from oauth2_provider.models import AbstractApplication, AccessToken


try:
    from urllib.parse import urljoin
except ImportError:
    from urlparse import urljoin


def application_logo(instance, filename):  # pylint: disable=unused-argument
    filename = filename.split('.')
    if len(filename) > 1:
        ext = filename[-1]
    else:
        ext = "png"
    return os.path.join("app_logo", uuid4().hex + "." + ext)


@python_2_unicode_compatible
class Application(AbstractApplication):
    
    class Meta:
        app_label = "auth_sys"
        db_table = "OAUTH2_PROVIDER_APPLICATION"
    """
    Extended oauth2_provider.models.AbstractApplication to include application description and logo
    """
    description = models.TextField()
    logo = models.ImageField(upload_to=application_logo, blank=True, null=True)
    is_anonymous = models.BooleanField(default=False,
                                       help_text='Valid for complete anonymous apps. Requires admin permission')
    required_scopes = models.CharField(max_length=256,
                                       help_text='Default non-tracking permissions. '
                                                 'Valid only if application is anonymous', null=True, blank=True)
    private_scopes = models.CharField(
        max_length=256, help_text='Private API scopes', null=True, blank=True)
    website = models.URLField(null=False, blank=False)
    privacy_policy = models.URLField(
        null=True, blank=True, help_text='Link of privacy policy of application')

    def get_logo_url(self):
        try:
            url = self.logo.url
            url = urljoin(settings.MEDIA_URL, url)
        except ValueError:
            url = None
        return url

    def get_absolute_url(self):
        return reverse('oauth2_provider:detail', args=[str(self.id)])

    def clean(self):
        super(Application, self).clean()
        if self.authorization_grant_type == AbstractApplication.GRANT_PASSWORD:
            error = _(
                "Resource owner password based grants are not allowed for now")
            raise ValidationError(error)

    def get_user_count(self):
        return AccessToken.objects.all().filter(application=self).values_list('user', flat=True).distinct().count()

    def __str__(self):
        if self.name:
            return self.name
        else:
            return self.client_id

auth_sys/forms.py
from django import forms
from django.db.models.fields import BLANK_CHOICE_DASH

from .models import Application


def get_choices_with_blank_dash(choices):
    return BLANK_CHOICE_DASH + list(choices)

# from django.utils import get_choices_with_blank_dash


class RegistrationForm(forms.ModelForm):
    name = forms.CharField(max_length=255, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    authorization_grant_type = forms.ChoiceField(choices=get_choices_with_blank_dash(Application.GRANT_TYPES[:2]),
                                                 widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Application
        fields = (
            'name', 'description', 'logo', 'website', 'privacy_policy', 'client_id', 'client_secret', 'client_type',
            'authorization_grant_type', 'redirect_uris')
        widgets = {
            'description': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 3, }
            ),
            'logo': forms.ClearableFileInput(
                attrs={'class': 'form-control', 'accept': 'image/*', }
            ),
            'website': forms.URLInput(
                attrs={'class': 'form-control', }
            ),
            'privacy_policy': forms.URLInput(
                attrs={'class': 'form-control', }
            ),
            'client_id': forms.TextInput(
                attrs={'class': 'form-control', }
            ),
            'client_secret': forms.TextInput(
                attrs={'class': 'form-control', }
            ),
            'client_type': forms.Select(
                attrs={'class': 'form-control', }
            ),
            'redirect_uris': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 4, }
            )
        }

auth_sys/views/oauth_token_redirect.py
'''
Created on Mar 6, 2018

@author: mtk06979
'''
import base64

from django.shortcuts import render

from auth_sys.models import Application
from oauth2_provider.models import Grant


def oauth_token_redirect(request):
    # Create your views here.
    code = request.GET.get("code")
    grant = Grant.objects.get(code=code)
    auth = "{}:{}".format(grant.application.client_id, grant.application.client_secret)
    encode_auth = base64.b64encode(auth.encode()).decode("ascii")

    return render(
        request,
        # front end will overwrite this template
        'oauth_redirect.html',  context={'AUTH_CODE': encode_auth}
    )

auth_sys/templates/oauth2_provider/application_detail.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block content %}
    <div class="block-center">
        <h3 class="block-center-heading">{{ application.name }}</h3>        
         <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                    {% static 'sso/img/default_logo.jpg' as default_image %}
                    <img class="media-object"
                         src="{{ application.get_logo_url|default_if_none:default_image}}" width="100" height="100" alt="Application Logo">
                </a>
            </div>
            {{ application.description }}
        </div>

        <ul class="unstyled">
            <li>
                <p><b>{% trans "Client id" %}</b></p>
                <input class="input-block-level" type="text" value="{{ application.client_id }}" readonly>
            </li>

            <li>
                <p><b>{% trans "Client secret" %}</b></p>
                <input class="input-block-level" type="text" value="{{ application.client_secret }}" readonly>
            </li>

            <li>
                <p><b>{% trans "Client type" %}</b></p>
                <p>{{ application.client_type }}</p>
            </li>

            <li>
                <p><b>{% trans "Authorization Grant Type" %}</b></p>
                <p>{{ application.authorization_grant_type }}</p>
            </li>

            <li>
                <p><b>{% trans "Redirect Uris" %}</b></p>
                <textarea class="input-block-level" readonly>{{ application.redirect_uris }}</textarea>
            </li>
        </ul>

        <div class="btn-toolbar">
            <a class="btn" href="{% url "oauth2_provider:list" %}">{% trans "Go Back" %}</a>
            <a class="btn btn-primary" href="{% url "oauth:update" application.id %}">{% trans "Edit" %}</a>
            <a class="btn btn-danger" href="{% url "oauth2_provider:delete" application.id %}">{% trans "Delete" %}</a>
        </div>
    </div>
{% endblock content %}

auth_sys/templates/oauth2_provider/application_form.html
{% extends "oauth2_provider/base.html" %}
{% load i18n %}

{% block content %}
    <div class="block-center">
        <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{% block app-form-action-url %}{% url 'oauth:update' application.id %}{% endblock app-form-action-url %}">
            <h3 class="block-center-heading">
                {% block app-form-title %}
                    {% trans "Edit application" %} {{ application.name }}
                {% endblock app-form-title %}
            </h3>
            {% csrf_token %}

            {% for field in form %}
                <div class="control-group {% if field.errors %}error{% endif %}">
                    <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <div class="controls">
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="help-inline">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}

            <div class="control-group {% if form.non_field_errors %}error{% endif %}">
                {% for error in form.non_field_errors %}
                    <span class="help-inline">{{ error }}</span>
                {% endfor %}
            </div>

            <div class="control-group">
                <div class="controls">
                    <a class="btn" href="{% block app-form-back-url %}{% url "oauth2_provider:detail" application.id %}{% endblock app-form-back-url %}">
                        {% trans "Go Back" %}
                    </a>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

auth_sys/templates/oauth2_provider/application_list.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block content %}
    <div class="block-center">
        <h3 class="block-center-heading">{% trans "Your applications" %}</h3>
        {% if applications %}
            <ul class="list-group">
                {% for application in applications %}
                    <li class="list-group-item">
                        <a href="{{ application.get_absolute_url }}">{{ application.name }}</a>
                        <span class="badge" title="users" data-toggle="tooltip" data-placement="right">{{ application.get_user_count }}</span>
                    </li> 
                {% endfor %}
            </ul>

            <a class="btn btn-success" href="{% url "oauth:register" %}">New Application</a>
        {% else %}
            <p>{% trans "No applications defined" %}. <a href="{% url 'oauth:register' %}">{% trans "Click here" %}</a> {% trans "if you want to register a new one" %}</p>
        {% endif %}
    </div>
{% endblock content %}

auth_sys/templates/oauth2_provider/application_registration_form.html
{% extends "oauth2_provider/application_form.html" %}

{% load i18n %}

{% block app-form-title %}{% trans "Register a new application" %}{% endblock app-form-title %}

{% block app-form-action-url %}{% url 'oauth:register' %}{% endblock app-form-action-url %}

{% block app-form-back-url %}{% url "oauth2_provider:list" %}"{% endblock app-form-back-url %}

auth_sys/templates/oauth2_provider/authorize.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% load staticfiles %}
{% load scope %}

{% block title %}
    Authorization
{% endblock %}

{% block content %}
    <div class="block-center">
        {% if not error %}
            <form id="authorizationForm" method="post">
                <div class="media">
                    <div class="media-left">
                        <a href="#">
                            {% static 'sso/img/default_logo.jpg' as default_image %}
                            <img class="media-object"
                                 src="{{ application.get_logo_url|default_if_none:default_image }}" width="100"
                                 height="100"
                                 alt="Application Logo">
                        </a>
                    </div>
                    <div class="media-body">
                        <h3 class="media-heading">{{ application.name }}</h3>
                        {{ application.description }}
                    </div>
                </div>
                <i>Developed by - <a href='mailto:{{ application.user.email }}'>{{ application.user.username }}</a></i>
                {% if application.website %}
                    <div><a href="{{ application.website }}" target="_blank">Visit website</a></div>
                {% endif %}
                {% if application.privacy_policy %}
                    <div><a href="{{ application.privacy_policy }}" target="_blank">Read privacy policies</a></div>
                {% endif %}
                {% csrf_token %}

                {% for field in form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <h3>{% trans "Application requires following permissions" %}</h3>

                <ul class="list-unstyled">

                    {% with zipped_scopes_description=scopes|zip:scopes_descriptions %}
                        {% for scope, description in zipped_scopes_description|get_basic_scope:application %}
                            <li>
                                <div class="checkbox">
                                    <label>
                                        <input checked disabled type="checkbox" id="{{ scope }}_scope"
                                               name="scopes_array"
                                               value="{{ scope }}"/>
                                        {{ description }}
                                    </label>
                                </div>
                            </li>
                        {% endfor %}
                        {% for scope, description in zipped_scopes_description|remove_basic_scope:application %}
                            <li>
                                <div class="checkbox">
                                    <label>
                                        <input checked type="checkbox" id="{{ scope }}_scope" name="scopes_array"
                                               value="{{ scope }}"/>
                                        {{ description }}
                                    </label>
                                </div>
                            </li>
                        {% endfor %}
                    {% endwith %}
                </ul>

                {{ form.errors }}
                {{ form.non_field_errors }}

                <div class="control-group">
                    <div class="controls">
                        <input type="submit" class="btn btn-large" value="Cancel"/>
                        <input type="submit" class="btn btn-large btn-primary" name="allow" value="Authorize"/>
                    </div>
                </div>
            </form>

        {% else %}
            <h2>Error: {{ error.error }}</h2>
            <p>{{ error.description }}</p>
        {% endif %}
    </div>
{% endblock %}

{% block jsLinks %}
    <script src="{% static 'oauth2_provider/js/authorize.js' %}" type="application/javascript"></script>
{% endblock %}